### ISSUE TITLE
Gazebo - Ogre crashes  (ros ticket #245)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_simulator#44]
I am getting following error, will investigate.

terminate called after throwing an instance of 'Ogre::InternalErrorException'
  what():  OGRE EXCEPTION(7:InternalErrorException): Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at OgreGLHardwareVertexBuffer.cpp (line 126)

trac data:
- Owner: **hsu**
- Reporter: **hsu**
- Reported at: **Tue Aug 26 19:05:57 2008**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/245

**Comment by ahendrix** [comment]
[hsu] two errors appear (see below).  they are caused by stereo camera in gazebo.  removed in latest revision.

```
XRequest.143: BadMatch (invalid parameter attributes) 0x5e0000e
```

and

```
terminate called after throwing an instance of 'Ogre::InternalErrorException'
  what():  OGRE EXCEPTION(7:InternalErrorException): Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at OgreGLHardwareVertexBuffer.cpp (line 126)
Abort (core dumped)


Program received signal SIGABRT, Aborted.
[Switching to Thread -1245010192 (LWP 12754)]
0xb726cfd6 in raise () from /lib/libc.so.6
(gdb) where
#0  0xb726cfd6 in raise () from /lib/libc.so.6
#1  0xb726e761 in abort () from /lib/libc.so.6
#2  0xb745a270 in __gnu_cxx::__verbose_terminate_handler () from /usr/lib/libstdc++.so.6
#3  0xb7457ca5 in ?? () from /usr/lib/libstdc++.so.6
#4  0xb7457ce2 in std::terminate () from /usr/lib/libstdc++.so.6
#5  0xb7457e1a in __cxa_throw () from /usr/lib/libstdc++.so.6
#6  0xb5b80fe2 in Ogre::GLHardwareVertexBuffer::lockImpl () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/RenderSystem_GL.so
#7  0xb5b7fff5 in Ogre::HardwareBuffer::lock () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/RenderSystem_GL.so
#8  0xb7dbd370 in Ogre::WireBoundingBox::setupBoundingBoxVertices () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#9  0xb7dbd72c in Ogre::WireBoundingBox::setupBoundingBox () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#10 0xb7d58faf in Ogre::SceneNode::_addBoundingBoxToQueue () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#11 0xb5aa3e55 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#12 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#13 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#14 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#15 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#16 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#17 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#18 0xb5aa3f24 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#19 0xb5aa3fe1 in Ogre::OctreeSceneManager::walkOctree () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#20 0xb5aa41fb in Ogre::OctreeSceneManager::_findVisibleObjects () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/OGRE/Plugin_OctreeSceneManager.so
#21 0xb7d30124 in Ogre::SceneManager::_renderScene () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#22 0xb7b6496e in Ogre::Camera::_renderScene () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#23 0xb7dbace0 in Ogre::Viewport::update () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#24 0xb7cf6733 in Ogre::RenderTarget::update () from /u/johnhsu/projects/pr2/3rdparty/ogre/ogre/lib/libOgreMain-1.4.9.so
#25 0x081084a4 in gazebo::StereoCameraSensor::UpdateChild (this=0x8ded798) at server/sensors/camera/StereoCameraSensor.cc:272
#26 0x0810f8e0 in gazebo::Sensor::Update (this=0x8ded798) at server/sensors/Sensor.cc:116
#27 0x080b8279 in gazebo::Body::Update (this=0x8ddbf40) at server/physics/Body.cc:236
#28 0x08146038 in gazebo::Model::Update (this=0x8c74250) at server/Model.cc:319
#29 0x08138493 in gazebo::World::Update (this=0x8aa7e58) at server/World.cc:203
#30 0x0814e0b6 in gazebo::Simulator::MainLoop (this=0x8184d20) at server/Simulator.cc:317
#31 0x08132449 in main (argc=Cannot access memory at address 0x31d2
) at server/main.cc:293
(gdb) 
```
