### ISSUE TITLE
wg_robot_description: roslaunch send.xml python error (urlp has no attribute 'port')  (ros ticket #299)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_simulator#59]
- on Debian4.0/ppc, following kinematic planning test procedure http://pr.willowgarage.com/wiki/Kinematic_motion_planning?highlight=%28planning%29%7C%28kinematic%29#head-d30bb328d94c992ae3c9d8ac431bf913457ca710
  - botherder started without problem
  - roscd wg_robot_description && roslaunch send.xml fails like this:
    {{{
    ... logging to  /home/rolo/ros/ros/log/roslaunch-21903.log
    ... resolving localhost master URI to http://127.0.1.1:11311/
    ... loading XML file [send.xml]
    ... executing command param [/home/rolo/ros/ros-pkg/robot_descriptions/wg_robot_
    description_parser/merge "/home/rolo/ros/ros-pkg/robot_descriptions/wg_robot_des
    cription/pr2/pr2.xml"]
    Added parameter [/robotdesc/pr2]
# SUMMARY

PARAMETERS
- /robotdesc/pr2

MACHINES

NODES

Traceback (most recent call last):
  File "/home/rolo/ros/ros/tools/roslaunch/src/roslaunch/**init**.py", line 127,
 in main
    rl.prelaunch_check()
  File "/home/rolo/ros/ros/tools/roslaunch/src/roslaunch/launch.py", line 154, i
n prelaunch_check
    self._prelaunch_check_master()
  File "/home/rolo/ros/ros/tools/roslaunch/src/roslaunch/launch.py", line 109, i
n _prelaunch_check_master
    if not urlp.port:
AttributeError: 'tuple' object has no attribute 'port'
}}}
- contents of /home/rolo/ros/ros/log/roslaunch-21903.log:
  {{{
  2008-09-16 13:02:09,951 rospy.topics INFO topicmanager initialized
  2008-09-16 13:02:10,143 roslaunch DEBUG add_param[/robotdesc/pr2]: type [<type '
  str'>]
  2008-09-16 13:02:10,211 rospy.core DEBUG signalShutdown start, reason [atexit]
  2008-09-16 13:02:10,212 rospy.core DEBUG signalShutdown: invoking shutdown hooks
  2008-09-16 13:02:10,212 rospy.core DEBUG signalShutdown: invoking <bound method 
  _TopicManager.shutdown of <rospy.topics._TopicManager object at 0x3030ecd0>>
  2008-09-16 13:02:10,212 rospy.core DEBUG signalShutdown done
  2008-09-16 13:02:10,313 process DEBUG pmon_shutdown: no pmons
  }}}

trac data:
- Owner: **sachinc**
- Reporter: **roland**
- Reported at: **Tue Sep 16 13:21:02 2008**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/299

**Comment by ahendrix** [comment]
[sachinc] closing this since it seems to have disappeared with the reformatting of the xml.
