### ISSUE TITLE
pr2_arm_test.xml startup error  (ros ticket #347)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_simulator#67]
mech.py and control.py does not get called as they are suppose to wait for service to come up and take effect in a nominal run.

{{{
bos:~/projects/pr2/robot_descriptions/gazebo_robot_description> roslaunch pr2_arm_test.xml
... logging to  /u/johnhsu/projects/ros/log/roslaunch-32739.log
... loading XML file [pr2_arm_test.xml]
... loading XML file [/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description/send_arm_test.xml]
... executing command param [/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description_parser/merge "/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description/pr2_arm_test/pr2_arm.xml"]
... done importing include file [/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description/send_arm_test.xml]
Added node of type [gazebo/gazebo] in namespace [/]
Added node of type [mechanism_control/mech.py] in namespace [/]
Added node of type [robot_mechanism_controllers/control.py] in namespace [/]
Added parameter [/robotdesc/pr2]
# SUMMARY

PARAMETERS
- /robotdesc/pr2

MACHINES

NODES
  /
    gazebo/gazebo
    mechanism_control/mech.py
    robot_mechanism_controllers/control.py

setting parameter [/robotdesc/pr2]
Creating process monitor thread
process[gazebo-1]: started with pid [32761]
process[mech.py-2]: started with pid [32765]
Gazebo multi-robot simulator, version 0.8-pre3

Part of the Player/Stage Project [http://playerstage.sourceforge.net].
Copyright (C) 2003 Nate Koenig, Andrew Howard, and contributors.
Released under the GNU General Public License.

process[control.py-3]: started with pid [301]
creating /tmp/gazebo-johnhsu-0
found a pid file: pid=32555
The gazebo process is not alive.
creating /tmp/gazebo-johnhsu-0/simulation.default 112 144496
... logging to  /u/johnhsu/projects/ros/log/mech.py-32765.log
Traceback (most recent call last):
  File "/u/johnhsu/projects/pr2/mechanism/mechanism_control/scripts/mech.py", line 35, in <module>
    mechanism.spawn_controller(xml)
  File "/u/johnhsu/ros/ros-pkg/mechanism/mechanism_control/src/mechanism_control/mechanism.py", line 28, in spawn_controller
    resp = s.call(SpawnControllerRequest(xml))
  File "/u/johnhsu/projects/ros/core/rospy/src/rospy/service.py", line 146, in call
    c.connect((dest_addr, dest_port))
  File "<string>", line 1, in connect
socket.error: (111, 'Connection refused')
-------------------- starting node in P3D 
creating /tmp/gazebo-johnhsu-0/position.p3d_object_position 112 228
Error Loading Controller[p3d_object_controller]
server/XMLConfig.cc:484 : Exception: unable to find required string attribute[topicName] in world file node[P3D]

deleting /tmp/gazebo-johnhsu-0/position.p3d_object_position
setting gravity to zero for: shoulder_pan_left
setting gravity to zero for: shoulder_pitch_left
setting gravity to zero for: upperarm_roll_left
setting gravity to zero for: elbow_flex_left
setting gravity to zero for: forearm_roll_left
creating /tmp/gazebo-johnhsu-0/camera.forearm_cam_left_iface 112 3145884
================= image_forearm_left
Unable to read value with key[imageSize]
Unable to read value with key[imageSize]
setting gravity to zero for: forearm_camera_left
setting gravity to zero for: wrist_flex_left
setting gravity to zero for: gripper_roll_left
setting gravity to zero for: finger_l_left
setting gravity to zero for: finger_tip_l_left
setting gravity to zero for: finger_r_left
setting gravity to zero for: finger_tip_r_left
creating /tmp/gazebo-johnhsu-0/camera.wrist_cam_left_iface 112 3145884
================= image_wrist_left
Unable to read value with key[imageSize]
Unable to read value with key[imageSize]
setting gravity to zero for: wrist_camera_left
[mech.py-2] process has died
creating /tmp/gazebo-johnhsu-0/audio.dummy_ros_time_iface_should_not_be_here 112 420
creating /tmp/gazebo-johnhsu-0/position.p3d_left_wrist_position 112 228
==== topic name for P3D ======== gripper_roll_left_pose
creating /tmp/gazebo-johnhsu-0/audio.gazebo_actuators_dummy_iface 112 420
Loading /u/johnhsu/projects/pr2/robot_descriptions/gazebo_robot_description/world/pr2_arm.xml
Loading /u/johnhsu/projects/pr2/robot_descriptions/gazebo_robot_description/world/gazebo_joints_arm.xml
Gazebo does not know about a joint named "base_joint"
... logging to  /u/johnhsu/projects/ros/log/control.py-301.log
Traceback (most recent call last):
  File "/u/johnhsu/projects/pr2/controllers/robot_mechanism_controllers/scripts/control.py", line 31, in <module>
    controllers.set_controller(sys.argv[2], float(sys.argv[3]))
  File "/u/johnhsu/projects/pr2/controllers/robot_mechanism_controllers/src/robot_mechanism_controllers/controllers.py", line 22, in set_controller
    resp = s.call(SetCommandRequest(command))
  File "/u/johnhsu/projects/ros/core/rospy/src/rospy/service.py", line 146, in call
    c.connect((dest_addr, dest_port))
  File "<string>", line 1, in connect
socket.error: (111, 'Connection refused')
[control.py-3] process has died
}}}

trac data:
- Owner: **hsu**
- Reporter: **hsu**
- Reported at: **Tue Sep 23 17:02:32 2008**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/347

**Comment by ahendrix** [comment]
[hsu] as opposed to a good start:

{{{
bos:~/projects/pr2/robot_descriptions/gazebo_robot_description> roslaunch pr2_arm_test.xml
... logging to  /u/johnhsu/projects/ros/log/roslaunch-867.log
... loading XML file [pr2_arm_test.xml]
... loading XML file [/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description/send_arm_test.xml]
... executing command param [/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description_parser/merge "/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description/pr2_arm_test/pr2_arm.xml"]
... done importing include file [/u/johnhsu/projects/pr2/robot_descriptions/wg_robot_description/send_arm_test.xml]
Added node of type [gazebo/gazebo] in namespace [/]
Added node of type [mechanism_control/mech.py] in namespace [/]
Added node of type [robot_mechanism_controllers/control.py] in namespace [/]
Added parameter [/robotdesc/pr2]

# SUMMARY

PARAMETERS
- /robotdesc/pr2

MACHINES

NODES
  /
    gazebo/gazebo
    mechanism_control/mech.py
    robot_mechanism_controllers/control.py

setting parameter [/robotdesc/pr2]
Creating process monitor thread
process[gazebo-1]: started with pid [892]
Gazebo multi-robot simulator, version 0.8-pre3

Part of the Player/Stage Project [http://playerstage.sourceforge.net].
Copyright (C) 2003 Nate Koenig, Andrew Howard, and contributors.
Released under the GNU General Public License.

process[mech.py-2]: started with pid [896]
process[control.py-3]: started with pid [915]
creating /tmp/gazebo-johnhsu-0
creating /tmp/gazebo-johnhsu-0/simulation.default 112 144496
... logging to  /u/johnhsu/projects/ros/log/mech.py-896.log
-------------------- starting node in P3D 
creating /tmp/gazebo-johnhsu-0/position.p3d_object_position 112 228
Error Loading Controller[p3d_object_controller]
server/XMLConfig.cc:484 : Exception: unable to find required string attribute[topicName] in world file node[P3D]

deleting /tmp/gazebo-johnhsu-0/position.p3d_object_position
setting gravity to zero for: shoulder_pan_left
setting gravity to zero for: shoulder_pitch_left
setting gravity to zero for: upperarm_roll_left
setting gravity to zero for: elbow_flex_left
setting gravity to zero for: forearm_roll_left
creating /tmp/gazebo-johnhsu-0/camera.forearm_cam_left_iface 112 3145884
================= image_forearm_left
Unable to read value with key[imageSize]
Unable to read value with key[imageSize]
setting gravity to zero for: forearm_camera_left
setting gravity to zero for: wrist_flex_left
setting gravity to zero for: gripper_roll_left
setting gravity to zero for: finger_l_left
setting gravity to zero for: finger_tip_l_left
setting gravity to zero for: finger_r_left
setting gravity to zero for: finger_tip_r_left
creating /tmp/gazebo-johnhsu-0/camera.wrist_cam_left_iface 112 3145884
================= image_wrist_left
Unable to read value with key[imageSize]
Unable to read value with key[imageSize]
setting gravity to zero for: wrist_camera_left
creating /tmp/gazebo-johnhsu-0/audio.dummy_ros_time_iface_should_not_be_here 112 420
creating /tmp/gazebo-johnhsu-0/position.p3d_left_wrist_position 112 228
==== topic name for P3D ======== gripper_roll_left_pose
creating /tmp/gazebo-johnhsu-0/audio.gazebo_actuators_dummy_iface 112 420
Loading /u/johnhsu/projects/pr2/robot_descriptions/gazebo_robot_description/world/pr2_arm.xml
Loading /u/johnhsu/projects/pr2/robot_descriptions/gazebo_robot_description/world/gazebo_joints_arm.xml
Gazebo does not know about a joint named "base_joint"
... logging to  /u/johnhsu/projects/ros/log/control.py-915.log
Controller node created
Spawning left_arm_controller: 0898a0ec
LOADING ARMCONTROLLERNODE
the prefix is left_arm_controller
JointPositionControllershoulder_pan_left_controller
JointPositionControllershoulder_pitch_left_controller
JointPositionControllerupperarm_roll_left_controller
JointPositionControllerelbow_flex_left_controller
JointPositionControllerforearm_roll_left_controller
JointPositionControllerwrist_flex_left_controller
JointPositionControllergripper_roll_left_controller
Listening to topic: left_arm_commands
Spawning gripper_left_controller: 0898a0ec
Listening to topic: left_gripper_commands
Spawned left_arm_controller
Spawned gripper_left_controller
[mech.py-2] process has died
0.5
[control.py-3] process has died
}}}

**Comment by ahendrix** [comment]
[hsu] more info: {{{... logging to  /u/johnhsu/projects/ros/log/mech.py-32765.log}
{{{
2008-09-23 15:33:24,943 rospy.topics INFO topicmanager initialized
2008-09-23 15:33:25,098 rospy.core DEBUG signalShutdown start, reason [atexit]
2008-09-23 15:33:25,098 rospy.core DEBUG signalShutdown: invoking shutdown hooks
2008-09-23 15:33:25,098 rospy.core DEBUG signalShutdown: invoking <bound method _TopicManager.shutdown of <rospy.topics._TopicManager object at 0xb78d92ac>>
2008-09-23 15:33:25,099 rospy.core DEBUG signalShutdown done
}}}

{{{... logging to  /u/johnhsu/projects/ros/log/control.py-301.log}
{{{
2008-09-23 15:33:25,406 rospy.topics INFO topicmanager initialized
2008-09-23 15:33:25,501 rospy.core DEBUG signalShutdown start, reason [atexit]
2008-09-23 15:33:25,502 rospy.core DEBUG signalShutdown: invoking shutdown hooks
2008-09-23 15:33:25,502 rospy.core DEBUG signalShutdown: invoking <bound method _TopicManager.shutdown of <rospy.topics._TopicManager object at 0xb7946fec>>
2008-09-23 15:33:25,502 rospy.core DEBUG signalShutdown done
}}}

**Comment by ahendrix** [comment]
[hsu] Ken,

can you take a look to see why mech.py crashes?  Thanks,

{{{
... logging to  /u/johnhsu/projects/ros/log/mech.py-32765.log
Traceback (most recent call last):
  File "/u/johnhsu/projects/pr2/mechanism/mechanism_control/scripts/mech.py", line 35, in <module>
    mechanism.spawn_controller(xml)
  File "/u/johnhsu/ros/ros-pkg/mechanism/mechanism_control/src/mechanism_control/mechanism.py", line 28, in spawn_controller
    resp = s.call(SpawnControllerRequest(xml))
  File "/u/johnhsu/projects/ros/core/rospy/src/rospy/service.py", line 146, in call
    c.connect((dest_addr, dest_port))
  File "<string>", line 1, in connect
socket.error: (111, 'Connection refused')
}}}

**Comment by ahendrix** [comment]
[hsu] Problem Cause:
Gazebo does not die cleanly, mech.py connects to an expired gazebo-mechanism-control service.
To repeat this error, follow the steps below:
- roslaunch pr2_arm_test.xml
- killall -9 gazebo
- ctrl-c in roslaunch windown
- roslaunch pr2_arm_test.xml

Have to think of a solution next.

**Comment by ahendrix** [comment]
[hsu] cleaned up gazebo mechanism control exit.
